```
-- management.v_camera definition

CREATE TABLE `v_camera` (
  `CAM_ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'TRIAL',
  `AREA_ID` bigint DEFAULT NULL COMMENT 'TRIAL',
  `CAM_CODE` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `CAM_NAME` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'TRIAL',
  `BRANCH` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `ORIGIN` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `DESCRIPTION` varchar(500) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `IS_ACTIVE` bigint DEFAULT '1' COMMENT 'TRIAL',
  `CREATED_BY` varchar(500) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT 'TRIAL',
  `MODIFIED_BY` varchar(500) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `MODIFY_DATE` datetime DEFAULT NULL COMMENT 'TRIAL',
  `STATUS` bigint DEFAULT '1' COMMENT 'TRIAL',
  `LOCATION` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `URL_LIVE_STREAM` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'TRIAL',
  `URL_SFTP` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `LOCATION_REAL_NAME` varchar(1000) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'TRIAL',
  `LOCATION_IMAGE` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci COMMENT 'TRIAL',
  `DIRECTION` varchar(500) CHARACTER SET utf8mb3 DEFAULT NULL,
  `TYPE` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `EXTERNAL_ID` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT 'ID_CAMERA_VMS',
  `URL_TIMELINE` varchar(500) CHARACTER SET utf8mb3 DEFAULT NULL,
  `PHYSICAL_DIRECTION` varchar(5000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `URL_THUMBNAIL` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CHANNEL_ID` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `FLOW_SECOND_LOCATION` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `URL_HLS` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`CAM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9999378 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='TRIAL';
```

```
-- management.v_area definition

CREATE TABLE `v_area` (
  `AREA_ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'TRIAL',
  `AREA_CODE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'TRIAL',
  `AREA_NAME` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'TRIAL',
  `PROVINCE` varchar(200) DEFAULT NULL COMMENT 'TRIAL',
  `DISTRICT` varchar(200) DEFAULT NULL COMMENT 'TRIAL',
  `VILLAGE` varchar(200) DEFAULT NULL COMMENT 'TRIAL',
  `DESCRIPTION` varchar(500) DEFAULT NULL COMMENT 'TRIAL',
  `IS_ACTIVE` bigint DEFAULT '1' COMMENT 'TRIAL',
  `CREATED_BY` varchar(500) DEFAULT NULL COMMENT 'TRIAL',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT 'TRIAL',
  `MODIFIED_BY` varchar(500) DEFAULT NULL COMMENT 'TRIAL',
  `MODIFY_DATE` datetime DEFAULT NULL COMMENT 'TRIAL',
  `STATUS` bigint DEFAULT '1' COMMENT 'TRIAL',
  `LOCATION` varchar(50) DEFAULT NULL COMMENT 'TRIAL',
  `SMS_LIST` varchar(1000) DEFAULT NULL COMMENT 'TRIAL',
  `province_new` varchar(200) DEFAULT NULL,
  `village_new` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`AREA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1308380 DEFAULT CHARSET=utf8mb3 COMMENT='TRIAL';
```

CREATE TABLE `v_area` (
  `AREA_ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'TRIAL',
  `AREA_CODE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'TRIAL',
  `AREA_NAME` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'TRIAL',
  `PROVINCE` varchar(200) DEFAULT NULL COMMENT 'TRIAL',
  `DISTRICT` varchar(200) DEFAULT NULL COMMENT 'TRIAL',
  `VILLAGE` varchar(200) DEFAULT NULL COMMENT 'TRIAL',
  `DESCRIPTION` varchar(500) DEFAULT NULL COMMENT 'TRIAL',
  `IS_ACTIVE` bigint DEFAULT '1' COMMENT 'TRIAL',
  `CREATED_BY` varchar(500) DEFAULT NULL COMMENT 'TRIAL',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT 'TRIAL',
  `MODIFIED_BY` varchar(500) DEFAULT NULL COMMENT 'TRIAL',
  `MODIFY_DATE` datetime DEFAULT NULL COMMENT 'TRIAL',
  `STATUS` bigint DEFAULT '1' COMMENT 'TRIAL',
  `LOCATION` varchar(50) DEFAULT NULL COMMENT 'TRIAL',
  `SMS_LIST` varchar(1000) DEFAULT NULL COMMENT 'TRIAL',
  `province_new` varchar(200) DEFAULT NULL,
  `village_new` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`AREA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1308380 DEFAULT CHARSET=utf8mb3 COMMENT='TRIAL';